name: Auto Assign and Update Issue Title
on:
  issues:
    types:
      - opened

jobs:
  auto-assign-and-update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Assign the issue and update the title
        uses: actions/github-script@v6
        with:
          script: |
            // Log the raw issue body for debugging
            console.log("Issue Body:", context.payload.issue.body);

            const issueBody = context.payload.issue.body;
            const issueTitle = context.payload.issue.title;

            // Extract the Game Version from the body
            const gameVersionMatch = issueBody.match(/Game version:\s*\n\s*- (.+?)\s*$/m);
            const gameVersion = gameVersionMatch ? gameVersionMatch[1].trim() : null;

            // Log the extracted game version for debugging
            console.log("Extracted Game Version:", gameVersion);

            if (gameVersion && gameVersion !== "Choose a game version") {
              // Append the game version in brackets to the issue title
              const updatedTitle = `${issueTitle} (${gameVersion})`;

              // Update the issue title
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                title: updatedTitle
              });

              console.log("Updated Title:", updatedTitle);
            } else {
              console.log("No valid game version selected or found.");
            }

            // Assign the issue to the specified user
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: ['leatrix']
            });
