name: Auto Assign and Update Issue Title
on:
  issues:
    types:
      - opened

jobs:
  auto-assign-and-update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Assign the issue and update the title
        uses: actions/github-script@v6
        with:
          script: |
            // Extract the issue body and title
            const issueBody = context.payload.issue.body;
            const issueTitle = context.payload.issue.title;

            // Debugging: Log the issue body to understand its format
            console.log("Issue Body:", issueBody);

            // Extract the game version using a simple regex pattern
            const gameVersionMatch = issueBody.match(/Game version:\s*\n\s*- (.+)/);
            const gameVersion = gameVersionMatch ? gameVersionMatch[1].trim() : null;

            // Debugging: Log the extracted game version
            console.log("Extracted Game Version:", gameVersion);

            // If a valid game version is found, update the title
            if (gameVersion && gameVersion !== "Choose a game version") {
              const updatedTitle = `${issueTitle} (${gameVersion})`;

              // Update the issue title
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                title: updatedTitle,
              });

              console.log("Updated Title:", updatedTitle);
            } else {
              console.log("No valid game version selected or found.");
            }

            // Assign the issue
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: ['leatrix'],
            });
