name: Debug Issue Body
on:
  issues:
    types:
      - opened

jobs:
  debug-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Log the Issue Body
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            console.log("Logged Issue Body:");
            console.log(issueBody);
