name: Auto Assign and Update Title
on:
  issues:
    types:
      - opened

jobs:
  auto-update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Title
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const issueTitle = context.payload.issue.title;

            // Adjusted regex to match "### Game version" followed by the value
            const gameVersionMatch = issueBody.match(/### Game version\n\n(.+)/);
            const gameVersion = gameVersionMatch ? gameVersionMatch[1].trim() : null;

            console.log("Extracted Game Version:", gameVersion);

            if (gameVersion) {
              const updatedTitle = `${issueTitle} (${gameVersion})`;

              // Update the title with the extracted game version
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                title: updatedTitle,
              });

              console.log("Updated Title:", updatedTitle);
            } else {
              console.log("No valid game version found.");
            }

            // Assign the issue to you
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: ['leatrix'],
            });
