name: Debug and Update Issue Title
on:
  issues:
    types:
      - opened

jobs:
  debug-and-update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Log Issue Body
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const issueTitle = context.payload.issue.title;

            console.log("Full Issue Body:");
            console.log(issueBody); // Log full issue body to inspect format

            // Attempt to capture the game version more flexibly
            const gameVersionMatch = issueBody.match(/### Game version[\s\S]*?([\w\s]+)/);
            const gameVersion = gameVersionMatch ? gameVersionMatch[1].trim() : null;

            console.log("Extracted Game Version:", gameVersion); // Log extracted game version

            if (gameVersion) {
              const updatedTitle = `${issueTitle} (${gameVersion})`;

              // Update the issue title
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                title: updatedTitle,
              });

              console.log("Updated Title:", updatedTitle); // Log updated title
            } else {
              console.log("No valid game version found.");
            }

            // Assign the issue
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: ['leatrix'],
            });
